# Generated by Django 4.1.7 on 2023-03-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=20)),
                ('phone_no', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=250)),
                ('aadhar_no', models.IntegerField()),
                ('license_no', models.IntegerField()),
                ('electionid_no', models.CharField(max_length=15)),
                ('rationcard_no', models.IntegerField()),
                ('Photo', models.ImageField(upload_to='usr_photo')),
            ],
        ),
    ]
