# Generated by Django 4.1.7 on 2023-03-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitecardapp', '0003_application_ration_approval_application_rto_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='admin_approval',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
