# Generated by Django 4.1.7 on 2023-03-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitecardapp', '0005_application_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='it_return_approval',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
